name: Build ISO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
  - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          lfs: true

      #- name: Use GitHub cache for Nix
      #  uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Show disk size
        run: |
          df -h
          lscpu
          sudo docker system prune -af; sudo docker volume prune -f; sudo docker builder prune --all -f
          docker system prune -af; docker volume prune -f; docker builder prune --all -f
          npm cache clean --force
          sudo npm cache clean --force
          sudo rm -rf /usr/local
          sudo rm -rf /usr/lib/jvm /usr/lib/google-cloud-sdk /usr/lib/llvm-* /usr/lib/firefox /usr/lib/gcc
          sudo rm -rf /usr/share/dotnet /usr/share/swift /usr/share/miniconda /usr/share/az_* /usr/share/gradle-*
          sudo rm -rf /opt
          sudo apt install nodejs
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          df -h

      #- name: Update flake.lock
      #  uses: DeterminateSystems/update-flake-lock@main
      #  with:
      #    pr-title: "Update flake.lock" # Title of PR to be created

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      - name: Build ISO
        run: |
          ./complete.sh
          git add -f stuff/nixpkgs.tar.zst
          timeout 40m nix build .#nixosConfigurations.iso.config.system.build.isoImage --fallback --max-substitution-jobs 32 -j 32 --option allow-import-from-derivation true --option extra-substituters https://install.determinate.systems --option extra-trusted-public-keys cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM= --option extra-experimental-features ca-derivations
          nix build .#nixosConfigurations.iso.config.system.build.isoImage --fallback --max-substitution-jobs 32 -j 32 --option allow-import-from-derivation true --option extra-substituters https://install.determinate.systems --option extra-trusted-public-keys cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM= --option extra-experimental-features ca-derivations
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: NixOS ISO
          path: result/iso
          if-no-files-found: error
          retention-days: 28

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.

