name: Build ISO (8GB version)

on:
  schedule:
  - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = flakes nix-command ca-derivations
            allow-import-from-derivation = true

      - uses: actions/checkout@v4

      - name: Show disk size
        run: |
          df -h
          lscpu
          sudo docker system prune -af; sudo docker volume prune -f; sudo docker builder prune --all -f
          docker system prune -af; docker volume prune -f; docker builder prune --all -f
          npm cache clean --force
          sudo npm cache clean --force
          sudo rm -rf /usr/local
          sudo rm -rf /usr/lib/jvm /usr/lib/google-cloud-sdk /usr/lib/llvm-* /usr/lib/firefox /usr/lib/gcc
          sudo rm -rf /usr/share/dotnet /usr/share/swift /usr/share/miniconda /usr/share/az_* /usr/share/gradle-*
          sudo rm -rf /opt
          sudo apt install nodejs
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          df -h

      - name: Build ISO
        run: |
          ./complete.sh
          git add -f stuff/nixpkgs.tar.zst
          nix build .#nixosConfigurations.iso8G.config.system.build.toplevel --fallback --max-substitution-jobs 32 -j 32 -o keep_deps
          nix-collect-garbage -d
          nix build .#nixosConfigurations.iso8G.config.system.build.isoImage --fallback

      - name: Upload ISO to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NixOS ISO
          path: result/iso
          if-no-files-found: error
          retention-days: 28

      # - name: Upload ISO to release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: iso8G
      #     files: result/iso/*.iso

